#!/usr/bin/env python
# encoding: utf-8

import os, platform
from optparse import OptionParser
from MultiLipsum.core import MultiLipsum

parser = OptionParser()
parser.add_option("-f", "--format", dest="format",
                  help="type of output words, sencences or paragraphs",
                  default="paragraphs",
                  choices=["words", "sentences", "paragraphs"])
parser.add_option("-n", "--number", dest="number", help="number of items to produce", default="1", type="int")
parser.add_option("-t", "--topic", dest="topic", help="topic for text, defaults to lipsum",
                  choices=["", "auto", "design", "finance"], default=None)
                  
(options, args) = parser.parse_args()

if options.topic is None:
  ml = MultiLipsum()
else:
  ml = MultiLipsum(options.topic)

method = getattr(ml, "get_%s" % options.format)
out = method(options.number)

if platform.system() in "Darwin":
  os.system("echo '%s' | pbcopy" % out)
  
print out